# Generated by Django 5.2.8 on 2025-11-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(blank=True)),
                ('Email_Address', models.EmailField(max_length=254, unique=True)),
                ('Date_of_Joining', models.DateField(default=True)),
            ],
        ),
    ]
