# Generated by Django 5.2.8 on 2025-11-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetable',
            name='Age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='Employee_Name',
            field=models.CharField(),
        ),
    ]
