# Generated by Django 5.2.8 on 2025-11-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_employeetable_age_alter_employeetable_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField()),
                ('Brand_Name', models.CharField(choices=[('Iphone', 'Apple'), ('Sliper', 'VKC')])),
                ('price', models.PositiveIntegerField()),
                ('Manufacturing_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
