# Generated by Django 5.2.8 on 2025-11-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Title', models.CharField()),
                ('Author_Name', models.CharField()),
                ('Genre', models.CharField(choices=[('m', 'comic'), ('f', 'love'), ('o', 'fiction')])),
                ('Published_Year', models.IntegerField()),
            ],
        ),
    ]
