# Generated by Django 5.2.8 on 2025-11-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_book_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='Genre',
            field=models.CharField(choices=[('m', 'comic'), ('f', 'love'), ('o', 'Action')]),
        ),
    ]
