# Generated by Django 5.2.8 on 2025-11-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_book_table_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Title', models.CharField()),
                ('Director_Name', models.CharField()),
                ('Date', models.DateField()),
                ('Language', models.CharField(default='English')),
            ],
        ),
    ]
