# Generated by Django 5.2.8 on 2025-11-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_movie_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField()),
                ('Age', models.IntegerField()),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Date_of_Birth', models.DateField()),
            ],
        ),
    ]
